location:
  exclude_from:
    - excludes/exclude-standard
  exclude_caches: true
  exclude_if_present:
    - .nobackup

storage:
  compression: lz4
  retries: 3
  retry_wait: 10
  archive_name_format: "{hostname}-{now}"

retention:
  keep_within: 3H
  keep_hourly: 24
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_yearly: 0
  prefix: "{hostname}-{now}"

hooks:
  before_backup:
    - echo "Starting a backup."

  before_prune:
    - echo "Starting pruning."

  before_compact:
    - echo "Starting compaction."

  before_check:
    - echo "Starting checks."

  after_backup:
    - echo "Finished a backup."

  after_compact:
    - echo "Finished compaction."

  after_prune:
    - echo "Finished pruning."

  after_check:
    - echo "Finished checks."

  after_extract:
    - echo "Finished extracting."

  on_error:
    - echo "Error during prune/compact/create/check."
