location:
  exclude_from:
    - common/exclude-standard
  exclude_caches: true # CACHEDIR.TAG
  exclude_if_present:
    - .nobackup
  repositories:
    - ${BORG_REPO}

storage:
  compression: lz4
  retries: 3
  retry_wait: 10
  archive_name_format: "{hostname}-{now}"
  relocated_repo_access_is_ok: true

retention:
  keep_within: 3H
  keep_hourly: 24
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_yearly: 0
  prefix: "{hostname}-{now}"

consistency:
  checks:
    - name: repository
    - name: archives
      frequency: 2 weeks

hooks:
  after_actions:
    - borg with-lock ${BORG_REPO} aws s3 sync ${BORG_REPO} s3://borg-home --delete
