<<: !include config.yaml

location:
  source_directories:
    - /home/edward
    - /mediaserver
    - /etc/netplan

storage:
  compression: lz4
  retries: 0

hooks:
  after_actions:
    - echo 'containers start'
    - cd /mediaserver; docker-compose start;

  on_error:
    - echo 'containers start'
    - cd /mediaserver; docker-compose start;